{
 "title": "Pando Recommender Demo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Default VPA (Container CPU Usage vs Requests)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$deployment.*\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Default VPA (Container Memory Usage vs Requests)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"$deployment.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\"$deployment.*\", resource=\"memory\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "VPA with Pando Recommender (Container CPU Usage vs Requests)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"pando-$deployment.*\", container!=\"\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\"pando-$deployment.*\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "VPA with Pando Recommender (Container Memory Usage vs Requests)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\"pando-$deployment.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "Usage"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\"pando-$deployment.*\", resource=\"memory\"})",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}