RECOMMENDER_NAME: 'pando'
DEFAULT_NAMESPACE: 'default'
PROM_URL: 'https://thanos-querier-openshift-monitoring.apps.ci-ln-xxxxx-xxxxx.aws-2.ci.openshift.org'
PROM_TOKEN: 'eyJhbGcxxx'
tree:
    0: theta
    1: theta
    2: linear
    3: kn
    4: theta
    5: theta
    6: naive
    7: naive
    8: theta
    9: theta
    10: theta
    11: theta
    12: theta
    13: theta
    14: theta
    15: theta

TARGET_PERCENTILE: 95
UPPERBOUND_PERCENTILE: 100
LOWERBOUND_PERCENTILE: 90
LIMIT: 5 #limiting maximum provisioning with respect to past usage
OUTPUT: False
STAT_THRESHOLD: 0.01
THETA_THRESHOLD: 0.001
WINDOW_SPLITTER: 0.7
MAX_CHANGEPOINTS: 5
FORECASTING_WINDOW: 300
FORECASTING_SIGHT: 3600
SAMPLING_PERIOD: 15
DEFAULT_UTILIZATION: 1000
SLEEP_WINDOW: 60