RECOMMENDER_NAME: 'pando'
DEFAULT_NAMESPACE: 'default'
PROM_URL: 'http://localhost:9090'
PROM_TOKEN: ''
tree:
    0: theta-sktime
    1: theta-sktime
    2: linear
    3: linear
    4: theta-sktime
    5: theta-sktime
    6: naive
    7: naive
    8: vpa
    9: vpa
    10: vpa
    11: vpa
    12: theta-sktime
    13: theta-sktime
    14: naive
    15: naive

TARGET_PERCENTILE: 90
UPPERBOUND_PERCENTILE: 95
LOWERBOUND_PERCENTILE: 50
LIMIT: 5 #limiting maximum provisioning with respect to past usage
OUTPUT: False
STAT_THRESHOLD: 0.01
THETA_THRESHOLD: 0.001
WINDOW_SPLITTER: 0.7
MAX_CHANGEPOINTS: 5
FORECASTING_WINDOW: 300
FORECASTING_SIGHT: 3600
SAMPLING_PERIOD: 15
DEFAULT_UTILIZATION: 1000
SLEEP_WINDOW: 120