apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: pando-test-periodic-vpa
spec:
  recommenders:
    - name: pando
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: pando-test-periodic
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 2
          memory: 1Gi
        controlledResources: ["cpu", "memory"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pando-test-periodic
spec:
  selector:
    matchLabels:
      app: pando-test-periodic
  replicas: 2
  template:
    metadata:
      labels:
        app: pando-test-periodic
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: pando-test-periodic
          image: quay.io/chenw615/periodic-load:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
            - "/periodic.sh"
            - "1200"
            - "600"
