apiVersion: v1
kind: ConfigMap
metadata:
  name: "recommender-config"
  namespace: openshift-vertical-pod-autoscaler
data:
  "recommender_config.yaml": |
    RECOMMENDER_NAME: "pando"
    DEFAULT_NAMESPACE: "${DEFAULT_NAMESPACE}"
    PROM_URL: "https://${PROM_HOST}"
    PROM_TOKEN: "${PROM_TOKEN}"
    tree:
        0: theta
        1: theta
        2: linear
        3: kn
        4: theta
        5: theta
        6: naive
        7: naive
        8: theta
        9: theta
        10: theta
        11: theta
        12: theta
        13: theta
        14: theta
        15: theta
    TARGET_PERCENTILE: 95
    UPPERBOUND_PERCENTILE: 100
    LOWERBOUND_PERCENTILE: 90
    LIMIT: 5
    OUTPUT: False
    STAT_THRESHOLD: 0.01
    THETA_THRESHOLD: 0.001
    WINDOW_SPLITTER: 0.7
    MAX_CHANGEPOINTS: 5
    FORECASTING_WINDOW: 300
    FORECASTING_SIGHT: 3600
    SAMPLING_PERIOD: 15
    DEFAULT_UTILIZATION: 1000
    SLEEP_WINDOW: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pando
  namespace: openshift-vertical-pod-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pando
  template:
    metadata:
      labels:
        app: pando
    spec:
      volumes:
        - name: pando-config
          configMap:
            name: recommender-config
      containers:
        - name: pando
          image: quay.io/chenw615/pando-recommender:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: pando-config
              mountPath: /predictive-vpa-recommenders/config
      serviceAccountName: predictive-recommender
      serviceAccount: predictive-recommender
