kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: predictive-recommender-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - serviceaccounts
  - events
  - configmaps
  - secrets
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  - verticalpodautoscalercheckpoints
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictive-recommender
  namespace: openshift-vertical-pod-autoscaler
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: predictive-recommender-role-binding
subjects:
- kind: ServiceAccount
  name: predictive-recommender
  namespace: openshift-vertical-pod-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: predictive-recommender-role